# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: MQTTX Web
version: "0.9.2"
slug: mqttx-web
description: MQTTX is a cross-platform MQTT 5.0 client toolbox that offers features such as scripts, benchmarks, data simulation, and AI-powered copilot. Learn how to connect, publish, subscribe, and use MQTTX with MQTT 5.0, 3.1.1, and 3.1.
url: "https://github.com/pengowray/addon-mqttx-web"
arch:
  - amd64
init: false
map:
  - share:rw
options:
  message: "Hello world..."
schema:
  message: "str?"
# image: "/home-assistant/amd64-addon-mqttx"
# image: "/home-assistant/{arch}-addon-example"
ingress: true
ingress_port: 8099
ingress_stream: true
