---
name: MQTTX Web
version: dev
slug: mqttx-web
description: The open platform for beautiful analytics and monitoring
url: https://github.com/pengowray/addon-mqttx-web
#codenotary: codenotary@frenck.dev
startup: services
ingress: true
ingress_port: 8099
ingress_stream: true
init: false
# panel_icon: mdi:chart-timeline
panel_title: MTTQX Web
arch:
  - aarch64
  - amd64
#  - armv7
map:
  - homeassistant_config
  - ssl
options:
  #env_vars: []
  add_user: true
  #certfile: fullchain.pem
  #keyfile: privkey.pem
schema:
  add_user: bool?
